### ISSUE TITLE
First usage, small issues

### ISSUE THREAD

**Issue by chrzyki** [cldf/cldf-buildbot#4]
Heya,

played around with this. I had to manually move (`cp config.py cldf-buildbot/`) the configuration to the `cldf-buildbot/` directory to make this work. In order to get the lexibank build to work, I had to change in said `config.py` line 93 `lexibank.check` to `check`. otherwise the build fails with `cldfbench: error: argument COMMAND: invalid choice: 'lexibank.check'`. After that the build is successful.

The cldf-dataset build fails as well because it tries to validate against `cldf-metadata.json` which doesn't exist for this dataset (it is `StructureDataset-metadata.json`). I think the code in `config.py` line 70 onwards 'wrongly' puts the cldf-dataset in the `self.org` lexibank? Not to familiar with the config.py though. :)

I know that this tool is a very new development, just wanted to provide initial feedback. Let me know if I can help with anything!

**Comment by xrotwang** [comment]
Yes, it's not production-ready yet. But you could already think about how to make this deployable within `appconfig`. It would require
- a virtualenv
- supervisor conf? or do we start/stop via fab task?
- an nginx proxy conf, including HTTP auth

**Comment by chrzyki** [comment]
Thanks, will have a look at how to make this deployable.
