### ISSUE TITLE
Discover CLDF metadata files

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf-buildbot#5]
It is surprisingly difficult to discover the available CLDF metadata files in a datasets' `cldf` directory - and pass these to `cldf validate` steps.

Maybe the simplest solution would be a `cldf validate` command that uses [`iter_datasets`](https://github.com/cldf/pycldf/blob/dc818701c2eb60a955cb3ce7e3b9f8246ac59af2/src/pycldf/dataset.py#L42) to validate **all** datasets found in a directory.

**Comment by SimonGreenhill** [comment]
hmm, I prefer the one command per dataset model, but I can see the use case here. Perhaps triggered with a '--all' flag? 

Can we assume that a metadata file ends in .json? as this will make `iter_datasets` much more efficient.

**Comment by xrotwang** [comment]
I've found a way to discover metadata files at configuration time (see #1 ).
