### ISSUE TITLE
Adapt for non-cldfbench curated datasets

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf-buildbot#7]
E.g. the dictionaria `Dictionary`s are not cldfbench-curated, but validation etc. could still be applied.

**Comment by xrotwang** [comment]
@SimonGreenhill @chrzyki @LinguList 
I think we are on the right track with buildbot. Just added per-org status pages (which was simple enough):

![Screenshot_2020-03-08 Buildbot(1)](https://user-images.githubusercontent.com/870184/76160007-87031880-6126-11ea-8a0a-4f235ea023a7.png)

**Comment by SimonGreenhill** [comment]
Awesome :)
